/**
 * Auto-generated OpenAPI types
 * Generated by: npm run client:generate
 * Source: docs/api-spec.yaml
 *
 * This file is auto-generated from the OpenAPI spec. Do not edit manually.
 * To regenerate, run: npm run client:generate
 */

/**
 * Placeholder types for OpenAPI paths
 * These will be replaced with actual types when client:generate runs
 */
export interface paths {
  [path: string]: Record<
    string,
    {
      requestBody?: {
        content: {
          'application/json': any;
        };
      };
      responses: Record<
        string,
        {
          content?: {
            'application/json': any;
          };
        }
      >;
    }
  >;
}
