/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check if the server is running and healthy
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Server health status */
                            status: string;
                            /** @description API version */
                            version: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full model
         * @description Retrieve the complete architecture model across all layers
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Model data retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Model manifest metadata */
                            manifest: {
                                [key: string]: unknown;
                            };
                            /** @description All layers in the model (key-value pairs mapping layer names to layer objects) */
                            layers: {
                                [key: string]: {
                                    [key: string]: unknown;
                                };
                            };
                            /** @description Total number of elements across all layers */
                            totalElements: number;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/layers/:layerName": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get layer
         * @description Retrieve a specific layer with all its elements
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    layerName: "motivation" | "business" | "security" | "application" | "technology" | "api" | "data-model" | "data-store" | "ux" | "navigation" | "apm" | "testing";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Layer retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Layer name */
                            name: string;
                            /** @description Layer elements (each element is an object with id, name, type, and properties) */
                            elements: {
                                [key: string]: unknown;
                            }[];
                            /** @description Total element count */
                            elementCount: number;
                        };
                    };
                };
                /** @description Layer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/elements/:id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get element
         * @description Retrieve a specific architecture element with its metadata and annotations
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Element retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Element ID (UUID for spec-aligned elements, semantic dot-ID for legacy elements) */
                            id: string;
                            /** @description Spec node type ID (e.g. motivation.goal) */
                            spec_node_id: string;
                            /** @description Element type (e.g. goal, endpoint) */
                            type: string;
                            /** @description Layer this element belongs to */
                            layer_id: string;
                            /** @description Element display name */
                            name: string;
                            /** @description Element description */
                            description?: string;
                            /** @description Typed attribute bag per spec-node schema */
                            attributes?: {
                                [key: string]: unknown;
                            };
                            /** @description Source file and symbol reference */
                            source_reference?: {
                                /** @enum {string} */
                                provenance: "extracted" | "manual" | "inferred" | "generated";
                                locations: {
                                    file: string;
                                    symbol?: string;
                                }[];
                                repository?: {
                                    url?: string;
                                    commit?: string;
                                };
                            };
                            /** @description Element metadata */
                            metadata?: {
                                created_at?: string;
                                updated_at?: string;
                                created_by?: string;
                                version?: number;
                            } & {
                                [key: string]: unknown;
                            };
                            /** @description Legacy flat properties (deprecated, use attributes) */
                            properties?: {
                                [key: string]: unknown;
                            };
                            /** @description Legacy semantic ID (deprecated, use id) */
                            elementId?: string;
                            /** @description Cross-layer references */
                            references?: unknown[];
                            /** @description Intra-layer relationships */
                            relationships?: unknown[];
                            /** @description Associated annotations */
                            annotations?: {
                                /** @description Annotation ID */
                                id: string;
                                /** @description Target element ID */
                                elementId: string;
                                /** @description Author name */
                                author: string;
                                /** @description Annotation content */
                                content: string;
                                /** @description Creation timestamp */
                                createdAt: string;
                                /** @description Last update timestamp */
                                updatedAt?: string;
                                /** @description Annotation tags */
                                tags?: string[];
                                /** @description Resolution status */
                                resolved?: boolean;
                                /** @description Annotation replies */
                                replies?: {
                                    id: string;
                                    author: string;
                                    content: string;
                                    createdAt: string;
                                }[];
                            }[];
                        };
                    };
                };
                /** @description Element not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get JSON schemas
         * @description Retrieve all JSON Schema definitions used by the system
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Schemas retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Spec version */
                            version: string;
                            /** @description Response type */
                            type: string;
                            /** @description Response description */
                            description: string;
                            /** @description Schema source */
                            source: string;
                            /** @description JSON schema definitions (each schema is a JSON Schema object) */
                            schemas: {
                                [key: string]: unknown;
                            };
                            /** @description Number of schemas */
                            schemaCount: number;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get annotations
         * @description Retrieve all annotations, optionally filtered by element
         */
        get: {
            parameters: {
                query?: {
                    elementId?: string;
                    author?: string;
                    tags?: string;
                    resolved?: "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Annotations retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description List of annotations */
                            annotations: {
                                /** @description Annotation ID */
                                id: string;
                                /** @description Target element ID */
                                elementId: string;
                                /** @description Author name */
                                author: string;
                                /** @description Annotation content */
                                content: string;
                                /** @description Creation timestamp */
                                createdAt: string;
                                /** @description Last update timestamp */
                                updatedAt?: string;
                                /** @description Annotation tags */
                                tags?: string[];
                                /** @description Resolution status */
                                resolved?: boolean;
                                /** @description Annotation replies */
                                replies?: {
                                    id: string;
                                    author: string;
                                    content: string;
                                    createdAt: string;
                                }[];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create annotation
         * @description Create a new annotation on a model element
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        elementId: string;
                        /** @default Anonymous */
                        author?: string;
                        content: string;
                        /** @default [] */
                        tags?: string[];
                    };
                };
            };
            responses: {
                /** @description Annotation created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Annotation ID */
                            id: string;
                            /** @description Target element ID */
                            elementId: string;
                            /** @description Author name */
                            author: string;
                            /** @description Annotation content */
                            content: string;
                            /** @description Creation timestamp */
                            createdAt: string;
                            /** @description Last update timestamp */
                            updatedAt?: string;
                            /** @description Annotation tags */
                            tags?: string[];
                            /** @description Resolution status */
                            resolved?: boolean;
                            /** @description Annotation replies */
                            replies?: {
                                id: string;
                                author: string;
                                content: string;
                                createdAt: string;
                            }[];
                        };
                    };
                };
                /** @description Invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
                /** @description Element not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/annotations/:annotationId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get annotation by ID
         * @description Retrieve a specific annotation by its ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    annotationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Annotation retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Annotation ID */
                            id: string;
                            /** @description Target element ID */
                            elementId: string;
                            /** @description Author name */
                            author: string;
                            /** @description Annotation content */
                            content: string;
                            /** @description Creation timestamp */
                            createdAt: string;
                            /** @description Last update timestamp */
                            updatedAt?: string;
                            /** @description Annotation tags */
                            tags?: string[];
                            /** @description Resolution status */
                            resolved?: boolean;
                            /** @description Annotation replies */
                            replies?: {
                                id: string;
                                author: string;
                                content: string;
                                createdAt: string;
                            }[];
                        };
                    };
                };
                /** @description Annotation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        /**
         * Update annotation (partial)
         * @description Update an existing annotation with partial fields (NOTE: partial updates, use PATCH for recommended behavior)
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    annotationId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        content?: string;
                        tags?: string[];
                        resolved?: boolean;
                    };
                };
            };
            responses: {
                /** @description Annotation updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Annotation ID */
                            id: string;
                            /** @description Target element ID */
                            elementId: string;
                            /** @description Author name */
                            author: string;
                            /** @description Annotation content */
                            content: string;
                            /** @description Creation timestamp */
                            createdAt: string;
                            /** @description Last update timestamp */
                            updatedAt?: string;
                            /** @description Annotation tags */
                            tags?: string[];
                            /** @description Resolution status */
                            resolved?: boolean;
                            /** @description Annotation replies */
                            replies?: {
                                id: string;
                                author: string;
                                content: string;
                                createdAt: string;
                            }[];
                        };
                    };
                };
                /** @description Annotation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete annotation
         * @description Delete an existing annotation
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    annotationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Annotation deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Annotation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Partially update annotation
         * @description Partially update an existing annotation (recommended over PUT)
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    annotationId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        content?: string;
                        tags?: string[];
                        resolved?: boolean;
                    };
                };
            };
            responses: {
                /** @description Annotation updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Annotation ID */
                            id: string;
                            /** @description Target element ID */
                            elementId: string;
                            /** @description Author name */
                            author: string;
                            /** @description Annotation content */
                            content: string;
                            /** @description Creation timestamp */
                            createdAt: string;
                            /** @description Last update timestamp */
                            updatedAt?: string;
                            /** @description Annotation tags */
                            tags?: string[];
                            /** @description Resolution status */
                            resolved?: boolean;
                            /** @description Annotation replies */
                            replies?: {
                                id: string;
                                author: string;
                                content: string;
                                createdAt: string;
                            }[];
                        };
                    };
                };
                /** @description Annotation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/annotations/:annotationId/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get annotation replies
         * @description Retrieve all replies to an annotation
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    annotationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Replies retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description List of replies */
                            replies: {
                                /** @description Reply ID */
                                id: string;
                                /** @description Author name */
                                author: string;
                                /** @description Reply content */
                                content: string;
                                /** @description Creation timestamp */
                                createdAt: string;
                            }[];
                        };
                    };
                };
                /** @description Annotation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create annotation reply
         * @description Add a reply to an annotation
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    annotationId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        author: string;
                        content: string;
                    };
                };
            };
            responses: {
                /** @description Reply created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Reply ID */
                            id: string;
                            /** @description Author name */
                            author: string;
                            /** @description Reply content */
                            content: string;
                            /** @description Creation timestamp */
                            createdAt: string;
                        };
                    };
                };
                /** @description Annotation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get changesets
         * @description Retrieve a list of all changesets
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Changesets retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            version: string;
                            changesets: {
                                [key: string]: {
                                    name: string;
                                    /** @enum {string} */
                                    status: "active" | "applied" | "abandoned";
                                    /** @enum {string} */
                                    type: "feature" | "bugfix" | "exploration";
                                    created_at: string;
                                    elements_count: number;
                                };
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changesets/:changesetId": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get changeset
         * @description Retrieve a specific changeset with all its changes
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    changesetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Changeset retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            metadata: {
                                id: string;
                                name: string;
                                description?: string;
                                /** @enum {string} */
                                type: "feature" | "bugfix" | "exploration";
                                /** @enum {string} */
                                status: "active" | "applied" | "abandoned";
                                created_at: string;
                                updated_at?: string;
                                workflow?: string;
                                summary: {
                                    elements_added: number;
                                    elements_updated: number;
                                    elements_deleted: number;
                                };
                            };
                            changes: {
                                version: string;
                                changes: {
                                    timestamp: string;
                                    /** @enum {string} */
                                    operation: "add" | "update" | "delete";
                                    element_id: string;
                                    layer: string;
                                    element_type: string;
                                    /** @description Element data (varies by element type) */
                                    data?: unknown;
                                    /** @description Previous element state (for update operations) */
                                    before?: unknown;
                                    /** @description New element state (for update operations) */
                                    after?: unknown;
                                }[];
                            };
                        };
                    };
                };
                /** @description Changeset not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Error message */
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
