/**
 * Error ID Constants
 * Unique identifiers for tracking errors across the application
 * Format: CATEGORY_SEQUENCE (e.g., JSONRPC_001, CHAT_001, WS_001)
 */

export const ERROR_IDS = {
  // JSON-RPC Handler Errors
  JSONRPC_MESSAGE_PARSE_FAILED: 'JSONRPC_001',
  JSONRPC_ATTACH_LISTENER_FAILED: 'JSONRPC_002',
  JSONRPC_ATTACH_LISTENER_BACKGROUND_FAILED: 'JSONRPC_003',
  JSONRPC_SEND_REQUEST_FAILED: 'JSONRPC_004',
  JSONRPC_SEND_NOTIFICATION_FAILED: 'JSONRPC_005',
  JSONRPC_NOTIFICATION_HANDLER_ERROR: 'JSONRPC_006',
  JSONRPC_HANDLE_NOTIFICATION_ERROR: 'JSONRPC_007',
  JSONRPC_MESSAGE_HANDLER_ERROR: 'JSONRPC_008',
  JSONRPC_WEBSOCKET_LOAD_FAILED: 'JSONRPC_009',
  JSONRPC_UNKNOWN_RESPONSE_ID: 'JSONRPC_010',

  // Chat Service Errors
  CHAT_GET_STATUS_FAILED: 'CHAT_001',
  CHAT_SEND_FAILED: 'CHAT_002',
  CHAT_CANCEL_FAILED: 'CHAT_003',

  // WebSocket Client Errors
  WS_CONNECTION_ERROR: 'WS_001',
  WS_MESSAGE_PARSE_FAILED: 'WS_002',
  WS_ERROR_EVENT: 'WS_003',
  WS_EVENT_HANDLER_ERROR: 'WS_004',
  WS_MAX_RECONNECT_ATTEMPTS: 'WS_005',
  WS_SEND_FAILED: 'WS_006',
  WS_NOT_CONNECTED: 'WS_007',

  // Data Loading Errors
  SPEC_CONVERSION_FAILED: 'DATA_001',
  DATA_LOADER_SUCCESS_CALLBACK_FAILED: 'DATA_002',
  DATA_LOADER_ERROR_CALLBACK_FAILED: 'DATA_003',

  // Annotation Errors
  ANNOTATION_CREATE_FAILED: 'ANNOTATION_001',
  ANNOTATION_DELETE_FAILED: 'ANNOTATION_002',
  ANNOTATION_RESOLVE_FAILED: 'ANNOTATION_003',
  ANNOTATION_REPLY_FAILED: 'ANNOTATION_004',
  ANNOTATION_DELETE_ROLLBACK_FAILED: 'ANNOTATION_005',

  // Session Storage Errors
  SESSION_STORAGE_PARSE_ERROR: 'STORAGE_001',
} as const;

export type ErrorId = typeof ERROR_IDS[keyof typeof ERROR_IDS];
