/**
 * Auto-generated Ladle Story Validation Tests
 *
 * Generated by: scripts/generate-story-tests.cjs
 * Total stories: 0
 *
 * DO NOT EDIT MANUALLY - Regenerate using:
 *   npm run test:stories:generate
 */

import { test, expect, Page } from '@playwright/test';
import type { ConsoleMessage } from '@playwright/test';
import { isExpectedConsoleError, isKnownRenderingBug } from './storyErrorFilters';

interface ValidationResult {
  consoleErrors: string[];
  pageErrors: string[];
  allowedErrors: string[];
  knownBugs: string[];
}

/**
 * Validates a story by checking for errors and basic rendering
 */
async function validateStory(
  page: Page,
  storyKey: string,
  storyName: string
): Promise<ValidationResult> {
  const consoleErrors: string[] = [];
  const pageErrors: string[] = [];
  const allowedErrors: string[] = [];
  const knownBugs: string[] = [];

  // ErrorBoundary "With error" story is SUPPOSED to trigger errors
  const shouldAllowErrors = storyName.includes('Errorboundary / With error');

  const consoleHandler = (msg: ConsoleMessage) => {
    if (msg.type() === 'error') {
      const text = msg.text();

      // Check if this is an expected error (silently filtered)
      if (shouldAllowErrors || isExpectedConsoleError(text)) {
        console.log(`[ALLOWED ERROR in "${storyName}"]: ${text}`);
        allowedErrors.push(text);
      } else if (isKnownRenderingBug(text)) {
        // Known rendering bugs - track but don't fail
        knownBugs.push(text);
      } else {
        consoleErrors.push(text);
      }
    }
  };

  const errorHandler = (error: Error) => {
    const message = error.message;
    if (shouldAllowErrors) {
      console.log(`[ALLOWED PAGE ERROR in "${storyName}"]: ${message}`);
      allowedErrors.push(message);
    } else {
      console.error(`[PAGE ERROR in "${storyName}"]: ${message}`);
      pageErrors.push(message);
    }
  };

  page.on('console', consoleHandler);
  page.on('pageerror', errorHandler);

  try {
    const url = `/?story=${storyKey}&mode=preview`;
    const response = await page.goto(url, {
      waitUntil: 'networkidle',
      timeout: 30000,
    });

    // Validate navigation succeeded with explicit null check
    if (!response) {
      throw new Error(`Navigation timed out for story "${storyName}"`);
    }

    // Validate HTTP response status
    const status = response.status();
    if (status !== 200) {
      throw new Error(`Story returned HTTP ${status} for story "${storyName}"`);
    }

    expect(status, `Story "${storyName}" failed to load`).toBe(200);

    // Wait for meaningful content to appear
    await page.locator(
      '[data-testid], [role="article"], .react-flow__node, h1, h2, h3, p, table, button, svg path'
    ).first().waitFor({ state: 'attached', timeout: 5000 }).catch(() => {});

    // For graph stories, wait for StoryLoadedWrapper or React Flow nodes
    const isGraphStory = /graphview(?!sidebar)|businesslayerview|specgraphview/i.test(storyKey);
    if (isGraphStory) {
      await page.locator('[data-storyloaded="true"]').waitFor({
        state: 'attached', timeout: 15000
      }).catch(() =>
        page.locator('.react-flow__node').first().waitFor({
          state: 'attached', timeout: 10000
        }).catch(() => {})
      );
    } else {
      await page.evaluate(() => new Promise(resolve => setTimeout(resolve, 200)));
    }

    const errorBoundary = await page.locator('[data-error-boundary]').count();

    if (!shouldAllowErrors) {
      expect(
        errorBoundary,
        `Story "${storyName}" triggered an error boundary`
      ).toBe(0);
    }

    // Content validation - story should render meaningful content
    if (!shouldAllowErrors) {
      const hasVisibleElements = await page.locator(
        '[data-testid], [role], .react-flow__node, .react-flow, h1, h2, h3, p, table, button, input, select, label, svg, img, canvas, [style*="border"], [style*="background"]'
      ).count();
      const bodyText = await page.locator('body').innerText();
      if (bodyText.trim().length < 2 && hasVisibleElements === 0) {
        knownBugs.push(`Story "${storyName}" rendered no meaningful content`);
      }
    }

    return { consoleErrors, pageErrors, allowedErrors, knownBugs };
  } finally {
    page.off('console', consoleHandler);
    page.off('pageerror', errorHandler);
  }
}

test.describe('Ladle Story Validation - All Stories', () => {
  test.describe.configure({ mode: 'parallel' });


});
